### PR TITLE
port circleparse changes

### LINKED ISSUE #18: Can't parse replays with ScoreV2 mod

### PR DESCRIPTION
**Pull request by tybug**
This is a port of the past two years (sounds more impressive than it really is) of changes over at the [circleparse](https://github.com/circleguard/circleparse) fork. After this circleparse will become defunct and [circleguard](https://github.com/circleguard/) will use osrparse instead.

There are quite a few changes here. The major ones are:

* add scorev2 mod (closes #18, supersedes #20)
* `mod_combination` is now a bitwise enum instead of a list of enums
* support for parsing "pure" lzma strings (no other information available besides the replay data, since the osu! api `/get_score` endpoint only gives us the replay data and nothing else)
* removal of the very last frame in replays after a certain version. This is the "rng seed" value. See the [osu! wiki](https://osu.ppy.sh/wiki/en/osu%21_File_Formats/Osr_%28file_format%29):
  > On replays set on version 20130319 or later, the 32-bit integer RNG seed used for the score will be encoded into an additional replay frame at the end of the LZMA stream, under the format -12345|0|0|seed.

### CODE REVIEW

**Comment by kszlim** [comment]
Since you're the defacto maintainer of osrparse now, I'll leave this up to you, but consider adding type annotations/mypy to this library since you're actively looking at it now. I've always found types pretty handy.

**Comment by tybug** [comment]
Good point. I've added type annotations to all public-facing members (adding them to internal methods doesn't seem worth the trouble).

**Comment by tybug** [comment]
@kszlim I'm afraid there's a merge rule setup on the master branch which means I can't merge without an approving review (and I can't approve my own pr). Up to you if you want to remove that rule or if you want to keep a rubber stamp on all future prs.

**Comment by kszlim** [comment]
@tybug removed it

**Pull request merged**
