### PR TITLE
Fix regular string parsing not returning anything

### PR DESCRIPTION
**Pull request by abraker95**
Resolves https://github.com/kszlim/osu-replay-parser/issues/17

### CODE REVIEW

**Comment by kszlim** [comment]
Seems like it breaks existing unit tests, please address my comment https://github.com/kszlim/osu-replay-parser/issues/17

Also, would be nice if you could add a test case for this please.

**Comment by abraker95** [comment]
What is confusing is that there is are tests like checking for player name, which require the reading of the regular strings, and that passing before this pr.

**Comment by kszlim** [comment]
Hmm, really not sure what you mean.

From the wiki:

```
Has three parts; a single byte which will be either 0x00, indicating that the next two parts are not present, or 0x0b (decimal 11), indicating that the next two parts are present. If it is 0x0b, there will then be a ULEB128, representing the byte length of the following string, and then the string itself, encoded in UTF-8. See UTF-8
```

Seems like the current implementation makes sense? If the byte is 0x00, we should increment the offset and not attempt to parse anything. Thus anything calling parse_string gets a None?

**Comment by abraker95** [comment]
Yes, parse_string returns a none and that's what I am having an issue with. If it returns a None, then how is the string read then?

Take this for instance:
```
def parse_player_name(self, replay_data):
     self.player_name = self.parse_string(replay_data)
```

I don't see it being assigned anywhere else, so self.player_name should be None then?

**Comment by kszlim** [comment]
Wouldn't that indicate the replay format is different from expected? I think that would mean the offset is incorrect. Probably shouldn't be adding parsing logic that runs contrary to the spec, but instead try to figure out why the offset is wrong in the first place.

I'm guessing that maybe the logic here https://github.com/ppy/osu/blob/master/osu.Game/Scoring/Legacy/LegacyScoreParser.cs#L78 isn't in the wiki, and that might be screwing up the offset with newer replays?

**Comment by abraker95** [comment]
Hmm good catch, I'll look into into it.

**Comment by tybug** [comment]
closing per https://github.com/kszlim/osu-replay-parser/issues/17#issuecomment-913050246 (tldr 'not our issue' for the moment)

**Pull request closed without merging**
